---

 - name: make rest calls to healthbot
   hosts: server
   gather_facts: no

   tasks: 

    - name: create device directory on your laptop
      local_action:
       module: file
       path: "{{playbook_dir}}/devices"
       state: directory

    - name: make rest calls to healthbot to add devices
      local_action:
       module: uri
       url: "https://{{ansible_host}}:8080/api/v1/device/{{item}}/"
       method: POST
       user: "{{ authuser }}"
       password: "{{ authpwd }}"
       HEADER_Content-Type: "application/json"
       HEADER_Accept: "application/json"
       force_basic_auth: yes
       validate_certs: no
       body: "{{ lookup('file','{{playbook_dir}}/devices/device_' + item) }}"
       body_format: json
      with_items: 
       - vmx105
       - vmx104

    - name: make rest call to healthbot to commit configuration
      local_action:
       module: uri
       url: "https://{{ansible_host}}:8080/api/v1/configuration"
       method: POST
       user: "{{ authuser }}"
       password: "{{ authpwd }}"
       HEADER_Accept: "application/json"
       force_basic_auth: yes
       validate_certs: no

    - name: make rest call to healthbot to get devices name
      local_action:
       module: uri
       url: "https://{{ansible_host}}:8080/api/v1/devices/"
       method: GET
       user: "{{ authuser }}"
       password: "{{ authpwd }}"
       HEADER_Content-Type: "application/json"
       HEADER_Accept: "application/json"
       force_basic_auth: yes
       validate_certs: no
       dest: "{{playbook_dir}}/devices/healthbot_running_config_for_devices.json"



